version: '3.8'
services:
  master:
    build: ./server
    container_name: master
    ports:
      - "8080:8080"
    depends_on:
      - slave1
      - slave2

  slave1:
    build: ./slave1
    container_name: slave1
    ports:
      - "8081:8081"

  slave2:
    build: ./slave2
    container_name: slave2
    ports:
      - "8082:8082"
